scapy/modules/p0f.py

The p0f module calls the `warning` function, without actually importing it.

Add missing import in p0f module

---

scapy/sendrecv.py
scapy/utils.py

* Fix some file descriptor leaks causing warnings when calling `sendpfast`
* Add a verbose parameter to `sendpfast` to optionally discard tcpreplay output
See commit messages.

sendpfast improvements

---

scapy/packet.py

Fixed functions pdfdump() and psdump() so that they now produce right side line drawing references to their corresponding hex components within the packet.

Updated packet.py - Fixed packet dumping for both PDF and EPS output.

---

doc/scapy/usage.rst

Removed untested comment for producing both PDF and PS packet output with functions pdfdump() and psdump().

Updated usage.rst

---

scapy/contrib/ikev2.py

If I execute the following commands in the scapy command line:
\>>> from scapy.contrib.ikev2 import *
\>>> IKEv2_payload_Transform(transform_type = 'Encryption', transform_id = 'AES-CBC')
I get the following exception:
Traceback (most recent call last):
File "/usr/lib/python3.4/code.py", line 90, in runcode
exec(code, self.locals)
File "<console>", line 1, in <module>
File "/usr/local/lib/python3.4/dist-packages/scapy/base_classes.py", line 199, in __call__
i.__init__(*args, **kargs)
File "/usr/local/lib/python3.4/dist-packages/scapy/packet.py", line 91, in __init__
self.fields[f] = self.get_field(f).any2i(self,fields[f])
File "/usr/local/lib/python3.4/dist-packages/scapy/fields.py", line 73, in any2i
return self.h2i(pkt, x)
File …

IKEv2_payload_Transform's transform_id is a MultiEnumField now

---

scapy/contrib/ikev2.py
test/ipsec.uts

This change is more complicated, so I think it deserves a pull request on it's own.
In IKEv2, the IKEv2 header and all payload headers contain a field next_payload that contains the number of the next payload in the list or 0 for the last payload. In scapy, this field should be set automatically by using the overload_fields. Since scapy uses a different class for each payload type, the overload_fields variable of every payload must contain an entry for every supported payload type and one extra entry for the IKEv2 header itself. Since these lists are quite large and monotonous, they should be calculated automatically.
ikev2.py already contains some code to calculate overload_fields, but its flawed:
- If a payload with number q follows a payload with number p, q should set p.next_payload …

Correctly calculate overload_fields of IKEv2 payload classes

---

scapy/arch/windows/__init__.py

Modified get_windows_if_list() in scapy\arch\windows\__init__.py to use Get-WMIObject instead of Get-NetAdapter which I confirmed to work on Windows 7, 8.1, Server 2012 R2 and Windows 10

Added WMI method for interface detection on Windows 7

---

scapy/fields.py

Converts the dict_keys object to a list before attempting to index into it.
Fixes issue #83
It turns out that the minimal test program I used fails now on a different `TypeError` now, but that's consistent with the (incorrect) behavior of the python2 scapy. (The `EnumField` constructor tries to be overly clever and mistakenly inverts the enum dictionary, thinking that the character values are meant to be the human readable strings, even though a `CharEnumField`'s internal representation is a character value).
Using an enum mapping character values to strings works fine after this change.

Fix TypeError in CharEnumField

---

scapy/sendrecv.py

Comparison of the default timeout None with 0 results in an error, un-orderable types.

[sendrecv.py] Fix comparison of default timeout.

---

scapy/layers/inet.py

This patch fixes an attempt to concat a string object with a byte object. Here's how to reproduce:
```
from scapy.all import *
p = Ether()/IP()/TCP()
p[TCP].options = [('NOP', None), ('NOP', None), ('Timestamp',
(695605763, 695605653)), ('NOP', None), ('NOP', None), ('SAck', (1931354576,
1931354603))]
bytes(p)
```

Fix error trying to concat string with byte type

---

scapy/utils.py

parse_usec returns the self.tsresol least significant integers of the passed time t. The result is the interpreted as microseconds. This is only true, if self.tsresol equals 6. If, for example, tsresol is 9, then an 8-digit number is returned that represents a timestamp in nanoseconds, but is then interpreted as microseconds. This happens for every tsresol other than 6.
This pull request normalizes the return value of parse_usec by pow(10, self.tsresol-6), ensuring that the portion of the timestamp smaller than a second is correctly returned in microsecond format. Thus, a nanosecond (tsresol=9) timescale will return 3 decimal spaces, while a millisecond timescale (tsresol=3) will append three zeros.

Correct usec calculation for tsresol other than 6.

---

scapy/sendrecv.py

A script that calls sniff may need to do cleanup of its own when the sniff gets terminated by the user. Right now sniff simply gobbles up the exception.

Make sniff reraise KeyboardInterrupt exception

---

LICENSE

Hi there,
scape is released under GPLv2 (see [here](https://github.com/secdev/scapy/blob/master/LICENSE)). This fork is therefore also licensed under GPLv2. This PR adds the appropriate license file to make this easier to spot.
Cheers,
tpltnt

explicit GPLv2 license

---

scapy/sendrecv.py

Make sure sniff always closes the L2socket even if it is interrupted by the user.

Always close sniff L2socket

---

scapy/data.py

The /etc/services file contains german umlauts on OpenSuse distributions. These are encoded as 0xf6, which ich the latin1 code for 'ö'.
It should be safe to ignore these invalid characters, as they _should_ (and are in this specific distribution) only be present in the description.

Ignore UTF-8 errors when loading /etc/services

---

scapy/utils.py

Before decode, input str should be encode.
use codecs.decode(bytes, 'hex')

import_hexcap: migrate to python3.x

---

scapy/layers/dns.py

In python3, inet_pton expects a utf string, not a bytestring as argument. Since pkt.rdata is a bytestring, it has to be decode to utf-8 before passing. 
Solves issue #102:
~~~~ ipython
In [1]: an=DNSRR(type='AAAA', rdata='2001::1')
In [2]: bytes(an)
Out[2]: b'\x00\x00\x1c\x00\x01\x00\x00\x00\x00\x00\x10 \x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
~~~~

decode the bytestring before passing to inet_pton()

---

scapy/arch/__init__.py
scapy/arch/linux.py

It's a copy of this PR: https://github.com/secdev/scapy/pull/43
To fix errors like this:
```
>>> sniff(iface='mon0', store=0, prn=update_time, filter='((wlan addr2 (3c:3e:3d:40:74:66 or c3:ee:fb:3a:10:f0) or wlan addr3 (3c:3e:3d:40:74:66 or c3:ee:fb:3a:10:f0)) and type mgt subtype probe-req) or (wlan addr1 30:3f:60:03:9c:01 and wlan addr3 (3c:3e:3d:40:74:66 or c0:ee:fb:9a:10:f0))')
tcpdump: 'addr2' is only supported on 802.11 with 802.11 headers
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.4/dist-packages/scapy/sendrecv.py", line 574, in sniff
s = L2socket(type=ETH_P_ALL, *arg, **karg)
File "/usr/local/lib/python3.4/dist-packages/scapy/arch/linux.py", line 479, in __init__
attach_filter(self.ins, filter)
File …
```

Use the provided interface in attach_filter()

---

README.md

Some inline link were having extra space that add some unwanted text
into the displayed readme file.

<README.md: Fix some MD typo>

---

scapy/route6.py

The original `conf.route6` was printing an empty table. This patch fixes the issue.
Example:
Before:
```
In [1]: conf.route6
Out[1]: 
```
After:
```
Welcome to Scapy (3.0.0) using IPython 5.1.0
In [1]: conf.route6
Out[1]: 
Destination                     Next Hop                    iface  src candidates
2001:xxx:xx:xx::xx:xx/127  ::                          eth0   2001:xx:xx:xx::xx:xx
fe80::/64                       ::                          eth0   fe80::xx:xx:xx
...
```
Side note: this is quite diverging from mainstream scapy, https://github.com/secdev/scapy/blob/master/scapy/route6.py#L55

Fixed conf.route6.__repr__

---

scapy/arch/windows/__init__.py

Changed Get-NetRoute cmdlet call to Get-WMIObject Win32_IP4RouteTable.
Win32_IP4RouteTable is available on older Windows versions as well.
Tested route collection on a Windows 10 and Windows 7 machine.
Improved the way windows determines his default interface (by utilizing the route table now)

Get routes improvements

---

scapy/layers/can.py
test/can.uts

Hi,
this is my first commit with the support for CAN. 
ISO14229 follows, as soon as I cleaned up the code.

add CAN support for Automotive Penetration Testing

---

scapy/layers/can.py

At the moment CAN layer `name` is set to be `SocketCAN`, which makes it quite inconsistent:
```python
c = CAN()
c.haslayer('CAN')  # 1
c.name  # 'SocketCAN'
c.getlayer('CAN')  # None
c['CAN']  # IndexError: Layer [CAN] not found
```
Changing the name to simply `CAN` fixes all these issues. I don't see any counter indication?

`CAN` layer class/name should be consistent

---

scapy/utils.py

One of the principle advantages of the PcapNG format is to support multiple interfaces, with potential different link types. This fix allows multiple link types to be decoded. Tested with a CAN + Ethernet capture file

Allow PcapNG reader to have multiple linktypes

---

scapy/layers/rtp.py

Fixes #192 by avoiding overloading the term "payload" - this shouldn't be the name of a field in layers.

Fix RTP fuzzing

---

scapy/arch/windows/__init__.py

The sprintf misbehaviour in the regression.uts file happened due to the "Loopback" interface not being "physically" available on Windows.
My changes simulate a loopback interface.
I tested whether routing (conf.route) and interface creation worked (show_interfaces()).
Also successfully performed some pings and arping using scapy.
Short snippet showing the routing table + iface table on Windows:
```Network         Netmask         Gateway         Iface           Output IP
0.0.0.0         0.0.0.0         192.168.192.1   Realtek PCIe GBE Family Controller 192.168.192.86 
127.0.0.0       255.0.0.0       0.0.0.0         lo0             127.0.0.1      
127.0.0.1       255.255.255.255 0.0.0.0         lo0             127.0.0.1      
127.255.255.255 255.255.255.255 0.0.0.0         lo0 …
```

Fixing sprintf regression.uts issue and some more

---

scapy/packet.py

Previously the copy() method didn't actually copy the packet's time field.

copy the packet timestamp as part of the copy() method

---

scapy/layers/inet.py

I think the expected type of oval should be bytes and checking if it's str is a leftover from Python 2 version. Without this change setting custom TCP options seems impossible because you either hit the continue statement or get an error when appending str to bytes in line 375.

Change expected TCP options type from str to bytes.

---

scapy/layers/inet6.py

In python2, map returns list object.
But in python3, map returns map object.
Modified map(...) -> list(map(...))

Fix TypeError becouse of python2-3 difference. This may solve Issue #217

---

scapy3k/sendrecv.py

This fixes erratic behavior when scapy is run inside of a separate
thread or in another process.
The patch is taken from
https://bitbucket.org/secdev/scapy/issues/473/scapy-sendrecv-selects-eintr-problem-in

Restart select when we see a EINTR

---

scapy3k/sendrecv.py

The problem was in exception handling for python3 which I missed. Fixing my commit.

Fix "Restart select when we see a EINTR" for python3
