phaethon/kamene

- doc/scapy/usage.rst
Updated the scapy usage documentation for lambda python3 syntax usage.
> Docs update for lambda syntax change in python3

- scapy/contrib/cdp.py
Tweaked a line in contrib/cdp.py because it was failing to load in python 3.5.
> Changed map to list comprehension for python3 compatibility.

- scapy/layers/ppp.py
- test/pppoe.uts
[pppoe.pcap.zip](https://github.com/phaethon/scapy/files/121179/pppoe.pcap.zip)
> Added PPPoED and LCP payloads

- scapy/layers/dot11.py
- test/dot11.uts
Expanding on the skeleton of dot11, will be adding more details to action frames and other frames, just want to make sure ongoing contributions merge back regularly.
> Add various new layers to dot11.py, add in a few unit tests to test different layers and fields.

- scapy/pipetool.py
- scapy/scapypipes.py
Hi, 
I ported pipelining to python3. 
BR,
Piotr
> support for python3

- scapy/layers/dhcp6.py
Relay Forward/Reply Messages are followed by a relay message option, which is
followed by any dhcp message.
This changes relay message options to expect dhcp messages in their
payload.
Also, the _DHCP6GuessPayload.guess_payload_class() method was doing
some voodoo with ord() before which - at least in my case - just broke.
Also, this defines fields_desc in DHCP6_RelayReply anstead of (ab)using
DHCP6_RelayForward for this like it was before.
I'd like to do some more cleanup here, move things into separate files
etc, but first I'd like to fix things :-)
> layers.dhcpv6: fix relay handling

- scapy/layers/dns.py
- test/regression.uts
Fix for #92. Ported patch by @jpmens and added testing of DNS over TCP. New test passes successfully.
> Add DNS over TCP support

- .gitignore
This makes it a little nicer for contributors using [PyCharm](https://www.jetbrains.com/pycharm/).
> Ignore PyCharm project files

- doc/scapy/installation.rst
Hi there,
I fixed some issues with the documentation of the installation. They include added links and minor changes.
Cheers,
tpltnt
> Installation doc fixes

- doc/scapy/advanced_usage.rst
Hi there,
I looked at the "Automata" section and fixed a few things.
Cheers,
tpltnt
> Automata docfix

- doc/scapy/installation.rst
Hi there,
I documented the (implicit) dependency on PyX and LaTeX for pdfdump() and psdump().
Cheers,
tplntn
> two more optional things documented

- doc/scapy/extending.rst
Hi there,
I fixed some minor issues in the documentation about extending scapy.
Cheers,
tpltnt
> Extension docfixes

- scapy/layers/inet.py
Hi there,
while reading through some chunks of inet.py I noticed very different formatting styles so I made the major part [PEP8](https://www.python.org/dev/peps/pep-0008/) compliant.
Cheers,
tpltnt
> inet style fixes

- test/run_tests
Hi there,
I had a short peek at ```run_tests``` and improved a few minor issues.
Cheers,
tpltnt
> improved run_tests

- doc/scapy/advanced_usage.rst
- doc/scapy/installation.rst
Hi phaeton,
I screened the documentation and fixed a few things which came to light due to the new theme.
Cheers,
tpltnt
> Theme docfixes

- doc/scapy/usage.rst
Hi there,
I added two links for Nestea attack in the documentation.
Cheers,
tpltnt
> Nestea links

- README.md
- scapy/contrib/doip.py
- test/regression.uts
Hi there,
I added basic support for Diagnostics over IP (DoIP), a protocol increasingly common in the automotive space.
Cheers,
tpltnt
> basic DoIP support

- scapy/arch/windows/__init__.py
Fix wrong indexing issue created at #50 
Should fix #163 and maybe #162 , #104 , #86
> Fix ifaces indexing issue

- appveyor.yml
- test/windows.uts
Created a first sample for CI Tests using appveyor.
For the windows specific stuff iam only executing the new windows.uts file.
It can be extended to support the regression.uts in the future (once it is working flawlessly on windows)
> Ci windows tests

- scapy/contrib/ospf.py
This commit fixes some of the python 3 conversions for OSPFv2. Mainly related to creating the checksums in relation to str() to bytes()
There are still some outstanding fixes required for OSPFv3 which I haven't tried to resolve.
> OSPFv2 fixes for python3

- .travis.yml
Work in progress to get Travis CI to correctly run all scapy3k tests.
> [WIP] Travis CI

- scapy/arch/windows/__init__.py
- scapy/sendrecv.py
Needed that to stop a sniffing capture from a thread when I was receiving no packet.
This is enabling to stop a sniffing at every loop.
> Add a stop_callback to stop sniffing without receiving packet

- kamene/sendrecv.py
backport from scapy
https://github.com/secdev/scapy/pull/757/commits/e39629aa22fab909f61900cd4b2b7b02810d7d12
> unwanted output in sr_loop

- bin/kamene.bat
- doc/kamene/build_dissect.rst
Fix #260, success in my own computer.
> Fix the path with quotations to support space included path
